/*
 * generated by Xtext
 */
package norwegiangambit.psqt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PSQTUiModule extends norwegiangambit.psqt.ui.AbstractPSQTUiModule {
	public PSQTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
