/*
 * generated by Xtext
 */
package norwegiangambit.psqt.ui.contentassist

import norwegiangambit.psqt.ui.contentassist.AbstractPSQTProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PSQTProposalProvider extends AbstractPSQTProposalProvider {
}
