/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class norwegiangambit_engine_Movegen */

#ifndef _Included_norwegiangambit_engine_Movegen
#define _Included_norwegiangambit_engine_Movegen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    copyMagic
 * Signature: ([I[J)V
 */
JNIEXPORT void JNICALL Java_norwegiangambit_engine_Movegen_copyMagic
  (JNIEnv *, jobject, jintArray, jlongArray);

/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    copyMaps
 * Signature: ([J[J)V
 */
JNIEXPORT void JNICALL Java_norwegiangambit_engine_Movegen_copyMaps
  (JNIEnv *, jobject, jlongArray, jlongArray);

/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    initVariables
 * Signature: (ZJJJJIJ)V
 */
JNIEXPORT void JNICALL Java_norwegiangambit_engine_Movegen_initVariables
  (JNIEnv *, jobject, jboolean, jlong, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    magicAtks
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_norwegiangambit_engine_Movegen_magicAtks
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_norwegiangambit_engine_Movegen_init
  (JNIEnv *, jobject);

/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    enemyAttacks
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_norwegiangambit_engine_Movegen_enemyAttacks
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     norwegiangambit_engine_Movegen
 * Method:    tzcnt2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_norwegiangambit_engine_Movegen_tzcnt2
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
