package norwegiangambit.engine.movegen;

import norwegiangambit.util.IConst;


public class MWR extends MRook{

	public static MRook QLINE,KLINE;
	public static MWR[] MOVES=new MWR[64];
	public static void init() {
		for (int from = 0; from < 64; from++) {
			MWR m = new MWR(from);
			m.SLIDES=m.rookSlides(from,IConst.WR,WCAPTURES);
			m.register(MOVEDATA.MD_R);
			MOVES[from] = m;
		}

		MWR q = MOVES[WR_QUEEN_STARTPOS];

		QLINE=new MSliderSpecial();
		QLINE.SLIDES=cline(q.SLIDES,CANCASTLE_WHITEQUEEN);
		QLINE.register(MOVEDATA.MD_RQW);
		QLINE.Q=MOVEDATAX.create(MOVEDATA.ALL[q.Q].bitmap^CANCASTLE_WHITEKING,CANCASTLE_BLACKQUEEN|CANCASTLE_WHITEQUEEN);

		MWR k = MOVES[WR_KING_STARTPOS];

		KLINE=new MSliderSpecial();
		KLINE.SLIDES=cline(k.SLIDES,CANCASTLE_WHITEKING);
		KLINE.register(MOVEDATA.MD_RKW);
		KLINE.K=MOVEDATAX.create(MOVEDATA.ALL[k.K].bitmap^CANCASTLE_WHITEQUEEN,CANCASTLE_BLACKKING|CANCASTLE_WHITEKING);

//		MWR q = MOVES[WR_QUEEN_STARTPOS];
//		QLINE=new MSliderSpecial();
//		QLINE.SLIDES=cline2(q,CANCASTLE_WHITEQUEEN,MOVEDATA.MD_RQW,MOVEDATA.MD_RQ,QLINE);
//		QLINE.Q=MOVEDATAX.create2(q.q.bitmap^CANCASTLE_WHITEKING,CANCASTLE_BLACKQUEEN|CANCASTLE_WHITEQUEEN,MOVEDATA.MD_RQ+84);
//		QLINE.K=MOVEDATA.MD_RQ+85;
//		MWR k = MOVES[WR_KING_STARTPOS];
//		KLINE=new MSliderSpecial();
//		KLINE.SLIDES=cline2(k,CANCASTLE_WHITEKING,MOVEDATA.MD_RKW,MOVEDATA.MD_RK,KLINE);
//		KLINE.Q=MOVEDATA.MD_RK+84;
//		KLINE.K=MOVEDATAX.create2(k.k.bitmap^CANCASTLE_WHITEQUEEN,CANCASTLE_BLACKKING|CANCASTLE_WHITEKING,MOVEDATA.MD_RK+85);
	}

	public MWR(int from) {
		super(from);
	}
}
