/*
 * generated by Xtext
 */
package norwegiangambit.psqt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PSQTRuntimeModule extends norwegiangambit.psqt.AbstractPSQTRuntimeModule {

}
