/*
* generated by Xtext
*/
package norwegiangambit.psqt.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PSQTAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("norwegiangambit/psqt/parser/antlr/internal/InternalPSQT.tokens");
	}
}
